"""Configuration values extracted from the notebook pipeline."""

SEQ_LEN = 16
FRAME_STRIDE = 16
USE_LOG = True
TEST_SIZE = 0.25
RANDOM_STATE = 42
ONLY_ONE_PERSON = False

DECLUTTER_MODE = "ema"
EMA_ALPHA = 0.98

USE_MAG = False
USE_DECLUTTERED_MAG = False
USE_MOTION_MAG = True
USE_LOCAL_VARIANCE = True
USE_PHASE_DIFF = True
LOCAL_VARIANCE_WINDOW = 9

BIN_START = 0
BIN_END = 120

ROOM_X = 4.8
ROOM_Y = 7.2
MAX_PEOPLE = 4

SELECTED_SENSORS = []
SELECTED_CHANNELS = [0, 4, 7, 11, 12, 15]

HEATMAP_H = 24
HEATMAP_W = 16
HEATMAP_SIGMA = 0.75

MATCH_THRESHOLD = 1.0
HEATMAP_THRESHOLD = 0.25
NMS_SIZE = 3
MAX_PERSONS = 4

TRAIN_BATCH_SIZE = 64
TRAIN_EPOCHS = 100
LEARNING_RATE = 1e-4
